version: '3.9'

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  logs:
    image: php:8.0-apache
    hostname: logs
    volumes:
      - ./logs/index.php:/var/www/html/index.php
      - ./pipeline:/var/www/html/logs

  #elasticsearch:
  #  image: "elasticsearch:8.1.0"
  #  hostname: "elasticsearch"
  #  ports:
  #    - "9200:9200"
  #    - "9300:9300"
  #  environment:
  #    - "discovery.type=single-node"
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    - "ELASTIC_PASSWORD=changeme"
  #  volumes:
  #    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#
  #kibana:
  #  image: "kibana:8.1.0"
  #  ports:
  #    - "5601:5601"
  #  volumes:
  #    - ./kibana.yml=/usr/share/kibana/config/kibana.yml
  #  depends_on:
  #    - elasticsearch
#
  #logstash:
  #  image: "logstash:8.1.0"
  #  volumes:
  #    - ./pipeline:/usr/share/logstash/pipeline
  #    - ./logstash.yml:/usr/share/logstash/config/logstash.yml
  #    #- ./logstash-sample.conf:/usr/share/logstash/config/logstash-sample.conf
  #  depends_on:
  #    - elasticsearch

  